import { Card, Divider, Layout, Modal, Steps, Typography } from "antd";
import { useCallback, useMemo, useState } from "react";

import { PrimerPaletteContext } from "./colors";
import DatasetStep from "./steps/DatasetStep";
import DiscoverStep from "./steps/DiscoverStep";

const { Title, Paragraph } = Typography;

const styles = {
    titleContainer: { display: "flex", gap: "1.5rem", justifyContent: "center" },
    title: { fontStyle: "italic", fontWeight: 300 },
    subtitle: { fontSize: 18, marginTop: 10, fontStyle: "italic", color: "#5F5F5F" },
    footer: { marginTop: 24 },
    footerParagraph: { color: "#8C8C8C" },
};

const stepItems = [
    {
        title: <strong>Choose or upload a dataset</strong>,
        description: "Use the default primer dataset or upload your own.",
    },
    {
        title: <strong>Discover primer sets</strong>,
        description: "Choose taxa for presence detection and find matching primer sets.",
    },
];

const App = () => {
    const [currentStep, setCurrentStep] = useState(0);
    const [dataset, setDataset] = useState(null);
    const [noticeVisible, setNoticeVisible] = useState(false);

    const onBack = useCallback(() => setCurrentStep(Math.max(0, currentStep - 1)), [currentStep]);
    const onNext = useCallback(
        () => setCurrentStep(Math.min(stepItems.length, currentStep + 1)),
        [currentStep]);

    /** @type ReactNode */
    const stepNode = useMemo(() => (
       <>
           <DatasetStep visible={currentStep === 0} dataset={dataset} setDataset={setDataset} onFinish={onNext} />
           <DiscoverStep visible={currentStep === 1} dataset={dataset} onBack={onBack} />
       </>
    ), [currentStep, dataset]);

    const showNotice = useCallback((e) => {
        e.preventDefault();
        setNoticeVisible(true);
    }, []);
    const hideNotice = useCallback(() => setNoticeVisible(false), []);

    return <Layout>
        <Layout.Content style={{minHeight: "100vh", padding: 36}}>
            <div style={{maxWidth: 1400, margin: "0 auto"}}>
                <Card>
                    <div style={styles.titleContainer}>
                        <Title level={1} style={styles.title}>SNIPe</Title>
                        <span style={styles.subtitle}>
                            <strong>S</strong>electing{" "}
                            <strong>N</strong>ovel{" "}
                            <strong>I</strong>nformative{" "}
                            <strong>P</strong>rimer-sets for{" "}
                            <strong>e</strong>-DNA
                        </span>
                    </div>
                    <div style={{ maxWidth: 600, margin: "0 auto" }}>
                        <Steps size="small" items={stepItems} current={currentStep} />
                    </div>
                    <Divider />
                    <PrimerPaletteContext.Provider value={dataset?.primerPalette}>
                        {stepNode}
                    </PrimerPaletteContext.Provider>
                </Card>
                <div style={styles.footer}>
                    <Paragraph style={styles.footerParagraph}>
                        This web application is designed to complement Tournayre <em>et al.</em> 2023. The data
                        presented here were generated by{" "}
                        <a href="https://oriannetournayre.wixsite.com/website" target="_blank" rel="noreferrer">
                            Orianne Tournayre
                        </a> and other members
                        of the{" "}
                        <a href="https://sclougheed.ca" target="_blank" rel="noreferrer">Lougheed Lab</a>.
                        The web application component is &copy;{" "}
                        <a href="https://dlougheed.com" target="_blank" rel="noreferrer">David Lougheed</a> 2023;
                        the{" "}
                        <a href="https://github.com/davidlougheed/snipe"
                           target="_blank"
                           rel="noreferrer">source code is available on Github</a>{" "}
                        under the terms of the{" "}
                        <a href="https://github.com/davidlougheed/snipe/blob/main/LICENSE"
                           target="_blank"
                           rel="noreferrer">GPL v3 license</a>; see the <a href="#" onClick={showNotice}>notice</a>.
                    </Paragraph>
                </div>
            </div>
            <Modal
                title="Copyright and License Notice"
                onCancel={hideNotice}
                footer={null}
                open={noticeVisible}
                width={640}
            >
                <Paragraph>
                    A web tool for optimally choosing eDNA primer pairs to identify a set of taxa. <br />
                    Copyright &copy; 2023 David Lougheed
                    (<a href="mailto:david.lougheed@gmail.com">david.lougheed@gmail.com</a>)
                </Paragraph>
                <Paragraph>
                    This program is free software: you can redistribute it and/or modify
                    it under the terms of the GNU General Public License as published by
                    the Free Software Foundation, either version 3 of the License, or
                    (at your option) any later version.
                </Paragraph>
                <Paragraph>
                    This program is distributed in the hope that it will be useful,
                    but WITHOUT ANY WARRANTY; without even the implied warranty of
                    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
                    GNU General Public License for more details.
                </Paragraph>
                <Paragraph>
                    You should have received a copy of the GNU General Public License
                    along with this program.
                    If not, see <a href="https://www.gnu.org/licenses/">https://www.gnu.org/licenses/</a>.
                </Paragraph>
            </Modal>
        </Layout.Content>
    </Layout>;
};

export default App;
