import { type ReactNode, useCallback, useState } from "react";
import { Modal, Typography } from "antd";
import packageJson from "../package.json";

const { Paragraph } = Typography;

const styles = {
    footer: { marginTop: 24 },
    footerParagraph: { color: "#8C8C8C" },
};

type GithubLinkProps = {
    children: ReactNode;
    subPath?: string;
};

const GitHubLink = ({ children, subPath }: GithubLinkProps) => (
    <a href={`https://github.com/davidlougheed/snipe${subPath || ""}`} target="_blank" rel="noreferrer">
        {children}
    </a>
);

const Footer = () => {
    const [noticeVisible, setNoticeVisible] = useState(false);

    const showNotice = useCallback((e) => {
        e.preventDefault();
        setNoticeVisible(true);
    }, []);
    const hideNotice = useCallback(() => setNoticeVisible(false), []);

    return (
        <>
            <div style={styles.footer}>
                <Paragraph style={styles.footerParagraph}>
                    This web application is designed to complement{" "}
                    <a
                        target="_blank"
                        rel="noreferrer noopener"
                        href="https://onlinelibrary.wiley.com/doi/10.1002/edn3.590"
                    >
                        Tournayre <em>et al.</em> (2024)
                    </a>
                    . The data presented here were generated by{" "}
                    <a href="https://oriannetournayre.wixsite.com/website" target="_blank" rel="noreferrer">
                        Orianne Tournayre
                    </a>{" "}
                    and other members of the{" "}
                    <a href="https://sclougheed.ca" target="_blank" rel="noreferrer">
                        Lougheed Lab
                    </a>
                    . The web application component is &copy;&nbsp;
                    <a href="https://dlougheed.com" target="_blank" rel="noreferrer">
                        David Lougheed
                    </a>{" "}
                    2023-2024; the <GitHubLink>source code is available on Github</GitHubLink> under the terms of
                    the <GitHubLink subPath="/blob/main/LICENSE">GPL v3 license</GitHubLink>; see the{" "}
                    <a href="#" onClick={showNotice}>
                        notice
                    </a>
                    .
                </Paragraph>
                <Paragraph style={styles.footerParagraph}>
                    Version {packageJson.version} &#x2E31; Please send any feedback or bug reports to{" "}
                    <a href="mailto:david.lougheed@gmail.com">david.lougheed@gmail.com</a> or file an issue on{" "}
                    <GitHubLink subPath="/issues">GitHub</GitHubLink>.
                </Paragraph>
            </div>

            <Modal
                title="Copyright and License Notice"
                onCancel={hideNotice}
                footer={null}
                open={noticeVisible}
                width={640}
            >
                <Paragraph>
                    A web tool for optimally choosing eDNA primer pairs to identify a set of taxa. <br />
                    Copyright &copy; 2023-2024 David Lougheed (
                    <a href="mailto:david.lougheed@gmail.com">david.lougheed@gmail.com</a>)
                </Paragraph>
                <Paragraph>
                    This program is free software: you can redistribute it and/or modify it under the terms of the
                    GNU General Public License as published by the Free Software Foundation, either version 3 of the
                    License, or (at your option) any later version.
                </Paragraph>
                <Paragraph>
                    This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
                    without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See
                    the GNU General Public License for more details.
                </Paragraph>
                <Paragraph>
                    You should have received a copy of the GNU General Public License along with this program. If
                    not, see <a href="https://www.gnu.org/licenses/">https://www.gnu.org/licenses/</a>.
                </Paragraph>
            </Modal>
        </>
    );
};

export default Footer;
